<?
$PERM["seller_personal_account"]["2"]="D";
$PERM["seller_personal_account"]["3"]="D";
$PERM["seller_personal_account"]["4"]="D";
$PERM["seller_personal_account"]["8"]="D";
$PERM["seller_personal_account"]["6"]="D";
$PERM["seller_personal_account"]["7"]="R";
$PERM["seller_personal_account"]["5"]="D";
$PERM["seller_personal_account"]["*"]="D";
$PERM["buyer_personal_account"]["6"]="R";
$PERM["buyer_personal_account"]["*"]="D";
$PERM["ads"]["8"]="W";
$PERM["ads"]["*"]="R";
$PERM["bitrix"]["8"]="D";
$PERM["bitrix"]["*"]="D";
$PERM["about"]["8"]="W";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>